;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(buffer-name-history extended-command-history))
(setq buffer-name-history '("*scratch*"))
(setq extended-command-history '("xah-fly-keys"))
(setq kill-ring '(#("test " 0 5 (fontified t))))
(setq search-ring 'nil)
(setq recentf-list 'nil)
